1. 你在设计一个卷积神经网络。对于每一层，请计算weights的个数，biases的个数，以及相应的特征图的大小。
   
   相关符号的含义如下：
   * CONV-K-N表示卷积核的个数为N，每个卷积核的大小为KxK，填充和步幅分别为0和1；
   * POOL-K表示一个KxK的池化层，步幅为K，填充为0；
   * FC-N表示一个全连接层，有N个神经元。
       
| Layer     | Activation map dimensions  | Number of weights  | Number of biases  |
| :----:    |  :-----------------------: | :----------------: | :--------------:  |
| INPUT     |  128x128x3                 |         0          |           0       |
| CONV-9-32 |                            |                    |                   |
| POOL-2    |                            |                    |                   |
| CONV-5-64 |                            |                    |                   |
| POOL-2    |                            |                    |                   |
| CONV-5-64 |                            |                    |                   |
| POOL-2    |                            |                    |                   |
| FC-3      |                            |                    |                   |



答：
* 输出形状为：$H'=\lfloor\tfrac{H-K+2P}{S}\rfloor+1=\lfloor\tfrac{H-K}{1}\rfloor+1=H-K+1$；#weights为$N\times K\times K\times C$，其中$C$为输入通道数，而#biases为$N$
* 注意池化层没有参数，而输出形状为：$H'=\lfloor\tfrac{H-K+2P}{S}\rfloor+1=\lfloor\tfrac{H-K}{K}\rfloor+1=\lfloor\tfrac{H}{K}\rfloor$
* 输出形状为：$N$。#weights为$M\times N$，其中$M$为输入向量的长度，而#biases为$N$

| Layer     | Activation map dimensions  | Number of weights  | Number of biases  |
| :----:    |  :-----------------------: | :----------------: | :--------------:  |
| INPUT     |  128x128x3                 |         0          |           0       |
| CONV-9-32 |  120x120x32                |      32x9x9x3      |          32       |
| POOL-2    |  60x60x32                  |      0             |          0        |
| CONV-5-64 |  56x56x64                  |      64x5x5x32     |  64               |
| POOL-2    |  28x28x64                  |      0             |   0               |
| CONV-5-64 |  24x24x64                  |      64x5x5x64     |   64              |
| POOL-2    |  12x12x64                  |      0             |  0                |
| FC-3      |  3                         |     3x12x12x64     |   3               |

2. 逻辑回归 / Logistic Regression

给定如下的逻辑回归，其中$(x_1,x_2)$为输入，$y$为相应的标签值（为0或者1）。

计算过程如下：

\begin{align*}
z&=w_1x_1+w_2x_2+b\\
a&=\sigma(z)
\end{align*}

其中，$\sigma(z)=\tfrac{1}{1+e^{-z}}$，同时，$L(a,y)=-(y\log a+(1-y)\log (1-a))$，其中，$\log$以自然底数$e$为底。

请回答如下的问题：

a. 请根据链式法则，给出$\tfrac{dL(a,y)}{dz}$的计算过程；

b. 若采取的是随机梯度下降算法，且学习率为1e-4，那么，在$(w_1,w_2,b)$为$(0.5,-0.5,0)$时，若$(x_1,x_2,y)$为$(1,1,0)$，则执行一次梯度下降迭代后，$(w_1,w_2,b)$为多少。请给出计算过程。

答：

a.

因为$\tfrac{dL(a,y)}{dz}=\tfrac{dL(a,y)}{da}\tfrac{da}{dz}$，这里先求解$\tfrac{da}{dz}$，有如下公式：

\begin{equation*}
\begin{split}
\frac{da}{dz}&=\frac{d\sigma(z)}{dz}\\
&=(-1)(1+e^{-z})^{-2}e^{-z}\\
&=\sigma(z)(1-\sigma(z))\\
&=a(1-a)
\end{split}
\end{equation*}

而对于$\tfrac{dL(a,y)}{da}$，有：

\begin{equation*}
\frac{dL(a,y)}{da}=-\frac{y}{a}+\frac{1-y}{1-a}
\end{equation*}

综上，有：$\tfrac{dL(a,y)}{dz}=a-y$。

b.

因为采取的是随机梯度下降算法，所以，需要计算如$\tfrac{\partial L(a,y)}{\partial w_1}$等的值。现在已经知道$\tfrac{dL(a,y)}{dz}=a-y$，而因为$y=0$，且$z=0.5\cdot 1-0.5\cdot 1+0=0$，所以$a=\sigma(z)=0.5$，$\tfrac{dL(a,y)}{dz}=0.5$。

这样的话，$\tfrac{\partial L(a,y)}{\partial w_1}=0.5x_1=0.5,\tfrac{\partial L(a,y)}{\partial w_2}=0.5x_2=0.5$，同时也有：$\tfrac{\partial L(a,y)}{\partial b}=0.5$。那么，经过一次梯度下降之后，$w_1=0.5-10^{-4}\cdot 0.5,w_2=-0.5-10^{-4}\cdot 0.5,b=-10^{-4}\cdot 0.5$。

3. 给定一个63x63x16的输入，并使用大小为7x7的32个卷积核进行卷积（步幅为2和无填充），请问输出是多少，为什么。

4. 给定输入的张量，形状为64x64x16，请问作用于其上的单个1x1的卷积核含有多少个参数（包括bias），为什么。

答：

3.

\begin{equation*}
\begin{split}
H'&=\lfloor\frac{H-K+2P}{S}\rfloor+1\\
&=\lfloor\frac{63-7+2\cdot 0}{2}\rfloor+1\\
&=29
\end{split}
\end{equation*}

所以，输出的形状为：$29\times 29\times 32$。

4.

weights包括16个参数，因为输入通道数为16；

bias包括1个参数，因为考虑的为单个的卷积核，输出通道数因此为1。

总的参数个数为17个。


5. 均方损失

给定如下的计算过程，其中$(x_1,x_2)$为输入，$y$为目标值：

\begin{align*}
z_1&=w_{11}x_1+w_{12}x_2+b_1\\
z_2&=w_{21}x_1+w_{22}x_2+b_2\\
a_1&=\mathrm{ReLU}(z_1)\\
a_2&=\mathrm{ReLU}(z_2)\\
a&=a_1w_{31}+a_2w_{32}
\end{align*}

而损失函数为均方损失，也就是说，$L(a,y)=\tfrac{1}{2}(a-y)^2$。

若采取的是随机梯度下降算法，且学习率为1e-4，那么，在$b_1=b_2=0$，$w_{11}=w_{12}=-1$，$w_{21}=w_{22}=1$，$w_{31}=w_{32}=1$时，若$(x_1,x_2,y)$为$(1,1,0.5)$，则执行一次梯度下降迭代后，$w_{21}$为多少。请给出计算过程。

答：

为执行一次梯度下降迭代，需要计算得到$\tfrac{\partial L(a,y)}{\partial w_{21}}$。

计算过程如下：

\begin{equation*}
\begin{split}
\frac{\partial L(a,y)}{\partial w_{21}}&=\frac{\partial L(a,y)}{\partial a}\frac{\partial a}{\partial a_2}\frac{\partial a_2}{\partial z_2}\frac{\partial z_2}{\partial w_{21}}\\
&=(a-y)w_{32}\frac{\partial a_2}{\partial z_2}x_1
\end{split}
\end{equation*}

因为$w_{21}=w_{22}=1$，且$b_2=0$，所以，$(x_1,x_2)=(1,1)$时，有：$z_2=1\cdot 1+1\cdot 1+0=2>0$，所以，$a_2=z_2=2$。

所以，可得到$\frac{\partial a_2}{\partial z_2}=1$。故：

\begin{equation*}
\frac{\partial L(a,y)}{\partial w_{21}}=(a-y)w_{32}\cdot 1\cdot x_1
\end{equation*}

同时，因为$z_1=-1\cdot 1-1\cdot 1+0<0$，所以，$z_1<0$。所以，$a_1=0$。因此，$a=0\cdot w_{31}+2\cdot 1=2$。

所以，

\begin{equation*}
\frac{\partial L(a,y)}{\partial w_{21}}=(2-0.5)\cdot 1\cdot 1\cdot 1=1.5
\end{equation*}

所以，执行一次梯度下降迭代后，$w_{21}=1-10^{-4}\cdot 1.5$。

6. 给定输入tensor `x`：

```
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]])
```

考虑卷积核`K`（注意bias为0）：

```
tensor([[-1.,  1.],
        [ 1.,  1.]])
```

a. 若stride为1，padding为0，那么，输出的tensor应该是什么？

b. 现在需要你用全连接层去替换掉上述卷积层，并得到和问题a相同的输出tensor。

那么，请问全连接层的weights和biases分别是什么。

答：

a.

若stride为1，padding为0，那么，输出的tensor应该是：

```
tensor([[10., 12., 14.]])
```

b.

注意从全连接层到卷积层，使用了平移不变性和局部性。

所以，首先卷积层所能表达的可以被全连接层所表达，只是前者增加了上述两个限制。

因此相应的全连接层的weights为：

```
tensor([[-1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.],
        [ 0., -1.,  1.,  0.,  0.,  1.,  1.,  0.],
        [ 0.,  0., -1.,  1.,  0.,  0.,  1.,  1.]])
```

因为问题a中卷积核函数的bias为0，因此，全连接层的biases也为0，即：

```
tensor([0., 0., 0.])
```


7. 多选题

注：考试题中无选择题

7.1 Which of the following techniques can be used to reduce model overfitting?

    a. Data augmentation
    b. Dropout
    c. Batch Normalization
    d. Using Adam instead of SGD
    
答：abc

7.2 Which of the following is true about dropout?

    a. Dropout leads to sparsity in the trained weights
    b. At test time, dropout is applied with inverted keep probability
    c. The larger the keep probability of a layer, the stronger the regularization of the weights in that layer
    d. None of the above

答：d

8. 循环神经网络

考虑循环神经网络中的通过时间反向传播，即backpropagation through time，BPTT。

这里，仅考虑RNN的weights和各输入$x_t$均为scalars的情况。

设RNN的每个时间步的隐状态和输出为：

\begin{align*}
h_t &= w_{hx}x_t+w_{hh}h_{t-1},\\
o_t &= w_{qh}h_t
\end{align*}

设输入序列为$(x_1,x_2,\dotsc,x_T)$，初始隐状态$h_0=0$，且损失函数为$L(o_T,y)$。

请推导得到一般的$\tfrac{\partial L(o_T,y)}{\partial w_{qh}}$，$\tfrac{\partial L(o_T,y)}{\partial w_{hx}}$，以及$\tfrac{\partial L(o_T,y)}{\partial w_{hh}}$的表达式。

同时，结合[通过时间反向传播](https://zh.d2l.ai/chapter_recurrent-neural-networks/bptt.html)分析：在本问题中，什么时候可能会发生梯度爆炸，什么时候可能会发生梯度消失。



答：

$\tfrac{\partial L(o_T,y)}{\partial w_{qh}}$为：

\begin{equation*}
\begin{split}
\frac{\partial L(o_T,y)}{\partial w_{qh}}&=\frac{\partial L(o_T,y)}{\partial o_T}\frac{\partial o_T}{\partial w_{qh}}\\
&=\frac{\partial L(o_T,y)}{\partial o_T}h_T
\end{split}
\end{equation*}

$\tfrac{\partial L(o_T,y)}{\partial w_{hx}}$为：

\begin{equation*}
\begin{split}
\frac{\partial L(o_T,y)}{\partial w_{hx}}&=\frac{\partial L(o_T,y)}{\partial o_T}\frac{\partial o_T}{\partial h_T}\frac{\partial h_T}{\partial w_{hx}}\\
&=\frac{\partial L(o_T,y)}{\partial o_T}w_{qh}\biggl(x_T+w_{hh}\frac{\partial h_{T-1}}{\partial w_{hx}}\biggr)
\end{split}
\end{equation*}

而类似的，$\tfrac{\partial h_{T-1}}{\partial w_{hx}}$为：

\begin{equation*}
\frac{\partial h_{T-1}}{\partial w_{hx}}=x_{T-1}+\frac{\partial h_{T-2}}{\partial w_{hx}}
\end{equation*}

代入并依次展开后得到：

\begin{equation*}
\begin{split}
\frac{\partial L(o_T,y)}{\partial w_{hx}}&=\frac{\partial L(o_T,y)}{\partial o_T}w_{qh}\bigl(x_T+w_{hh}x_{T-1}+w^2_{hh}x_{T-2}+\dotsb\bigr)\\
&=\frac{\partial L(o_T,y)}{\partial o_T}w_{qh}\sum_t w^t_{hh}x_{T-t}
\end{split}
\end{equation*}

最后，$\tfrac{\partial L(o_T,y)}{\partial w_{hh}}$为：

\begin{equation*}
\begin{split}
\frac{\partial L(o_T,y)}{\partial w_{hh}}&=\frac{\partial L(o_T,y)}{\partial o_T}\frac{\partial o_T}{\partial h_T}\frac{\partial h_T}{\partial w_{hh}}\\
&=\frac{\partial L(o_T,y)}{\partial o_T}\frac{\partial o_T}{\partial h_T}\biggl(h_{T-1}+w_{hh}\frac{\partial h_{T-1}}{\partial w_{hh}}\biggr)
\end{split}
\end{equation*}

而类似的，$\tfrac{\partial h_{T-1}}{\partial w_{hh}}$为：

\begin{equation*}
\frac{\partial h_{T-1}}{\partial w_{hh}}=h_{T-2}+w_{hh}\frac{\partial h_{T-2}}{\partial w_{hh}}
\end{equation*}

代入并依次展开后得到：

\begin{equation*}
\begin{split}
\frac{\partial L(o_T,y)}{\partial w_{hh}}&=\frac{\partial L(o_T,y)}{\partial o_T}\frac{\partial o_T}{\partial h_T}(h_{T-1}+w_{hh}h_{T-2}+w^2_{hh}h_{T-3}+\dotsb)\\
&=\frac{\partial L(o_T,y)}{\partial o_T}\frac{\partial o_T}{\partial h_T}\sum_t w^t_{hh}h_{T-t-1}
\end{split}
\end{equation*}

从$\tfrac{\partial L(o_T,y)}{\partial w_{hx}}$，以及$\tfrac{\partial L(o_T,y)}{\partial w_{hh}}$的表达式可以观察到，梯度的形式中有$w_{hh}$的潜在的非常大的幂。

对于$w_{hh}<1$的情况来说，这将意味着梯度消失；对于$w_{hh}>1$的情况来说，这将意味着梯度爆炸。

9. PyTorch的编程

请利用PyTorch框架，编程实现Dropout、LayerNorm（仅针对全连接层的输出）、BatchNorm（仅针对全连接层的输出）。

相关的函数接口如下：

Dropout

`def dropout(input, p=0.5, training=True)`

LayerNorm

`def layer_norm1d(input, gamma, beta, eps=1e-05)`

BatchNorm

`def batch_norm1d(input, gamma, beta, moving_mean, moving_var, eps=1e-05, momentum=0.1, training=True)`

答：

Dropout

```
def dropout(input, p=0.5, training=True):
    if training or p == 0:
        return X
    if p == 1:
        return torch.zeros_like(X)
    mask = torch.rand(X.shape) > p
    return mask.astype(torch.float32) * X / (1.0 - p)
```

LayerNorm

```
def layer_norm1d(input, gamma, beta, eps=1e-05):
    mean = input.mean(-1, keepdim=True)
    var = input.var(-1, keepdim=True)
    return gamma * (x - mean) / (var + eps).sqrt() + beta
```

BatchNorm

```
def batch_norm1d(input, gamma, beta, moving_mean, moving_var, eps=1e-05, momentum=0.1, training=True):
    if not training:
        # 预测模式
        input_hat = (input - moving_mean) / torch.sqrt(moving_var + eps)
    else:
        mean = input.mean(dim=0)
        var = input.var(dim=0)
        
        # 训练模式
        input_hat = (input - mean) / (var + eps).sqrt()
        # 更新移动平均的均值和方差
        moving_mean = momentum * moving_mean + (1.0 - momentum) * mean.detach()
        moving_var = momentum * moving_var + (1.0 - momentum) * var.detach()
        
    output = gamma * input_hat + beta
    return output, moving_mean, moving_var
```

