# 课程安排
1_课程安排.pdf
# 安装
3_安装.pdf

# 成绩比例
- 1次presentation（10分钟）（10%），2次大作业 + 课堂回答问题（30%）
- 期末考试（60%）

# 数据操作

1. 获取数据
1. 将数据读入计算机后对其进行处理

1. $n$维数组，也称为*张量*（tensor）（Python中NumPy计算包）
1. 但深度学习框架又比Numpy的`ndarray`多一些重要功能：
    1. GPU很好地支持加速计算，而NumPy仅支持CPU计算
    1. 张量类支持自动微分
    
4_数据操作.pdf（Page 1、2 / N维数组样例）

## 入门

导入`torch`

In [16]:
import torch

张量表示由一个数值组成的数组，这个数组可能有多个维度

1. *向量*（vector）
1. *矩阵*（matrix）
1. ...

1. 可以使用 `arange` 创建一个行向量 `x`
1. 默认创建为整数（也可指定创建类型为浮点数）
1. 除非额外指定，新的张量将存储在内存中，并采用基于CPU的计算

In [17]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

张量的`shape`属性

In [18]:
x.shape

torch.Size([12])

张量中元素的总数，即形状的所有元素乘积

In [19]:
x.numel()

12

改变一个张量的形状：`reshape`函数

（理解的要点：多层嵌套的`for`循环）

In [20]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

可以通过`-1`来调用自动计算出维度的功能（用`x.reshape(-1, 4)`或`x.reshape(3, -1)`来取代`x.reshape(3, 4)`）

1. 初始化：例如使用全0、全1、其他常量，或者从特定分布中随机采样的数字
1. 4_数据操作.pdf（Page 3 / 创建数组）

In [21]:
print(torch.zeros((2, 3, 4)))
print(torch.ones((2, 3, 4)))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


当我们构造数组来作为神经网络中的参数时，我们通常会随机初始化参数的值

（$\mathcal{N}(x|\mu,\sigma^2)$）

In [22]:
# $\mu=0,sigma=1$
torch.randn(3, 4)

tensor([[-0.2779,  1.2154,  0.1313,  0.8327],
        [ 1.2468,  3.2303, -0.6407, -1.2773],
        [ 0.2040,  0.8540, -0.4994, -0.7015]])

我们还可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值

In [23]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算符

1. 在这些数据上执行数学运算
1. 最简单且最有用的操作是*按元素*（elementwise）运算（将标准标量运算符应用于数组的每个元素）
1. 对于任意具有相同形状的张量，常见的标准算术运算符（`+`、`-`、`*`、`/`和`**`）都可以被升级为按元素运算

In [24]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

1. “按元素”方式可以应用更多的计算，包括像求幂这样的一元运算符
1. 除了按元素计算外，我们还可以执行线性代数运算，包括向量点积和矩阵乘法

In [25]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

1. 也可以把多个张量*连结*（concatenate）在一起
1. 只需要提供张量列表，并给出沿哪个轴连结

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

*逻辑运算符*

In [27]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和

In [28]:
X.sum()

tensor(66.)

## 广播机制

在某些情况下，即使形状不同，我们仍然可以通过调用
*广播机制*（broadcasting mechanism）来执行按元素操作：
1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状。
1. 对生成的数组执行按元素操作

In [29]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

1. 由于`a`和`b`分别是$3\times1$和$1\times2$矩阵，如果让它们相加，它们的形状不匹配
2. 我们将两个矩阵*广播*为一个更大的$3\times2$矩阵
3. （给出tricky的做法）

In [30]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片

张量中的元素可以通过索引访问
1. 第一个元素的索引是0
1. 最后一个元素索引是-1

4_数据操作.pdf（Page 4 / 访问元素）

1. 用`[-1]`选择最后一个元素
1. 用`[1:3]`选择第二个和第三个元素

In [34]:
print(X)
X[0:2, 1:3]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[1., 2.],
        [5., 6.]])

除读取外，我们还可以通过指定索引来将元素写入矩阵

In [35]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

1. 如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值
1. 例如，`[0:2, :]`访问第1行和第2行，其中“:”代表沿轴1的所有元素

In [36]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

1. 运行一些操作可能会导致为新结果分配内存
1. 例如，如果我们用`Y = X + Y`，我们将取消引用`Y`指向的张量，而是指向新分配的内存处的张量
1. Python的`id()`函数：提供内存中引用对象的确切地址

In [37]:
before = id(Y)
Y = Y + X
id(Y) == before

False

1. 我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们希望原地执行这些更新。
1. 如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

### 执行原地操作

我们可以使用切片表示法将操作的结果分配给先前分配的数组

In [40]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140608819702720
id(Z): 140608819702720


如果在后续计算中没有重复使用`X`，
我们也可以使用`X[:] = X + Y`或`X += Y`来减少操作的内存开销

In [ ]:
before = id(X)
X += Y
id(X) == before

## 转换为其他Python对象

1. torch张量和numpy数组将共享它们的底层内存
1. 就地操作更改一个张量也会同时更改另一个张量
1. `.numpy()`
1. 要将大小为1的张量转换为Python标量，我们可以调用`item`函数或Python的内置函数

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

## 小结

* 深度学习存储和操作数据的主要接口是张量（$n$维数组）
* 它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象